"""Fail-closed execution guards for reviewed local and provider runs.

These guards are deliberately engine-neutral.  They establish the resource
and time boundaries around an attempt; they do not claim GPU residency or
turn process persistence into warm weights.  In particular, the warm-reuse
expectation is a typed policy field and never depends on a listener port.
"""

from __future__ import annotations

import shutil
import hashlib
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Mapping


class ExecutionGuardError(RuntimeError):
    """Base error raised when an execution allowance cannot be established."""


class ScratchFloorError(ExecutionGuardError):
    """The filesystem does not have the required free-space floor."""


class EvidenceCapError(ExecutionGuardError):
    """Generated attempt evidence exceeds its declared cap."""


class ExecutionDeadlineError(ExecutionGuardError):
    """An attempt crossed its host-owned execution deadline."""


class WarmReuseExpectationError(ExecutionGuardError):
    """The warm-reuse policy is malformed."""


SCRATCH_FLOOR_BYTES = 4 * 1024**3
GENERATED_EVIDENCE_CAP_BYTES = 2 * 1024**3
DEFAULT_DEADLINE_SECONDS = 3600.0


class EvidenceBudget:
    """Accumulate generated bytes across attempts owned by one host run."""

    def __init__(self) -> None:
        self._lock = threading.RLock()
        self._charged_bytes = 0
        self._attempt_bytes: dict[str, int] = {}
        self._exhausted = False
        self._breach: dict[str, int] | None = None

    @property
    def charged_bytes(self) -> int:
        with self._lock:
            return self._charged_bytes

    @property
    def exhausted(self) -> bool:
        with self._lock:
            return self._exhausted

    @property
    def breach(self) -> dict[str, int] | None:
        with self._lock:
            return dict(self._breach) if self._breach is not None else None

    def assert_available(self) -> None:
        with self._lock:
            if self._exhausted:
                raise EvidenceCapError("generated evidence run budget is exhausted")

    def account(self, key: str, observed_bytes: int, cap_bytes: int) -> dict[str, int]:
        with self._lock:
            self.assert_available()
            previous = self._attempt_bytes.get(key, 0)
            delta = max(0, int(observed_bytes) - previous)
            if self._charged_bytes + delta > cap_bytes:
                self._exhausted = True
                self._breach = {
                    "attempt_observed_bytes": int(observed_bytes),
                    "run_observed_bytes": self._charged_bytes + delta,
                    "cap_bytes": int(cap_bytes),
                }
                raise EvidenceCapError(
                    f"generated evidence run budget "
                    f"{self._charged_bytes + delta} exceeds cap {cap_bytes}"
                )
            self._attempt_bytes[key] = max(previous, int(observed_bytes))
            self._charged_bytes += delta
            return {
                "attempt_delta_bytes": delta,
                "run_observed_bytes": self._charged_bytes,
            }


@dataclass(frozen=True, slots=True)
class ExecutionGuardPolicy:
    """Bound one attempt with explicit disk, evidence, and deadline limits."""

    scratch_floor_bytes: int = SCRATCH_FLOOR_BYTES
    evidence_cap_bytes: int = GENERATED_EVIDENCE_CAP_BYTES
    deadline_seconds: float = DEFAULT_DEADLINE_SECONDS
    warm_reuse_expected: bool = False
    evidence_budget: EvidenceBudget = field(
        default_factory=EvidenceBudget,
        compare=False,
        repr=False,
    )

    def __post_init__(self) -> None:
        if self.scratch_floor_bytes <= 0:
            raise ValueError("scratch_floor_bytes must be positive")
        if self.evidence_cap_bytes <= 0:
            raise ValueError("evidence_cap_bytes must be positive")
        if self.deadline_seconds <= 0:
            raise ValueError("deadline_seconds must be positive")
        if type(self.warm_reuse_expected) is not bool:
            raise WarmReuseExpectationError("warm_reuse_expected must be a boolean")

    def assert_scratch_floor(self, path: str | Path) -> dict[str, Any]:
        """Require the filesystem backing ``path`` to retain the free-space floor."""
        root = Path(path)
        try:
            free_bytes = int(shutil.disk_usage(root).free)
        except OSError as exc:
            raise ScratchFloorError(f"cannot measure scratch filesystem: {root}") from exc
        if free_bytes < self.scratch_floor_bytes:
            raise ScratchFloorError(
                f"scratch free space {free_bytes} is below required floor "
                f"{self.scratch_floor_bytes} at {root}"
            )
        return {
            "path": str(root),
            "free_bytes": free_bytes,
            "required_bytes": self.scratch_floor_bytes,
        }

    def immutable_input_baseline(self, root: str | Path) -> dict[str, tuple[int, str]]:
        """Capture materialized input bytes before the child is launched."""
        directory = Path(root)
        if not directory.exists():
            return {}
        baseline: dict[str, tuple[int, str]] = {}
        for path in directory.rglob("*"):
            if path.is_symlink() or not path.is_file():
                continue
            payload = path.read_bytes()
            baseline[str(path.resolve())] = (
                len(payload),
                hashlib.sha256(payload).hexdigest(),
            )
        return baseline

    def evidence_bytes(
        self,
        root: str | Path,
        *,
        immutable_inputs: Mapping[str, tuple[int, str]] | None = None,
    ) -> int:
        """Count generated bytes without following symlink escapes.

        Bytes present in the immutable input baseline are excluded; growth of
        an input file after the baseline is still charged as generated data.
        """
        directory = Path(root)
        if not directory.exists():
            raise EvidenceCapError(f"evidence root does not exist: {directory}")
        baseline = immutable_inputs or {}
        total = 0
        try:
            for path in directory.rglob("*"):
                if path.is_symlink() or not path.is_file():
                    continue
                size = int(path.stat().st_size)
                identity = baseline.get(str(path.resolve()))
                if identity is not None:
                    expected_size, expected_digest = identity
                    actual_digest = hashlib.sha256(path.read_bytes()).hexdigest()
                    if size == expected_size and actual_digest == expected_digest:
                        continue
                total += size
        except OSError as exc:
            raise EvidenceCapError(f"cannot measure generated evidence: {directory}") from exc
        return total

    def assert_evidence_cap(
        self,
        root: str | Path,
        *,
        immutable_inputs: Mapping[str, tuple[int, str]] | None = None,
    ) -> dict[str, Any]:
        """Reject generated evidence beyond the cumulative run-wide cap."""
        observed_bytes = self.evidence_bytes(root, immutable_inputs=immutable_inputs)
        accounting = self.evidence_budget.account(
            str(Path(root).resolve()),
            observed_bytes,
            self.evidence_cap_bytes,
        )
        return {
            "root": str(Path(root)),
            "observed_bytes": observed_bytes,
            "cap_bytes": self.evidence_cap_bytes,
            **accounting,
        }

    def assert_budget_available(self) -> None:
        self.evidence_budget.assert_available()

    def deadline_from_now(self) -> float:
        return time.monotonic() + self.deadline_seconds

    @staticmethod
    def deadline_expired(deadline: float) -> bool:
        return time.monotonic() >= deadline

    def assert_deadline(self, deadline: float) -> None:
        if self.deadline_expired(deadline):
            raise ExecutionDeadlineError(
                f"execution exceeded {self.deadline_seconds:g}s deadline"
            )

    def warm_expectation(self, *, listener_port: int | None = None) -> dict[str, Any]:
        """Return warm policy evidence without requiring a listener endpoint."""
        if listener_port is not None and not 1 <= int(listener_port) <= 65535:
            raise WarmReuseExpectationError("listener_port must be in the TCP port range")
        return {
            "warm_reuse_expected": self.warm_reuse_expected,
            "listener_port": listener_port,
            "port_independent": True,
        }
